# Generated by Django 5.2.9 on 2026-05-12 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_detectionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionhistory',
            name='image_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
