version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/media:/app/media
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings

  frontend:
    build:
      context: ./frontend
    ports:
      - "8081:8081"
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
      - REACT_NATIVE_PACKAGER_HOSTNAME=192.168.192.77
